### ISSUE TITLE
macOS Catalina update?

### ISSUE THREAD

**Issue by diogosantos** [sbooth/Max#18] opened 2019-08-20 17:48 UTC
Hey guys, I just installed Catalina and sadly they don't allow Max to run anymore. How can I survive with the best wav to mp3 converter that exists?

**Comment by HansVanEijsden** [comment] 2019-08-21 00:27
Ooooh are you serious? Max is one of the most used programs on my Macs. I'm sure I won't upgrade to Catalina if Max won't run.
I've tried to rebuild Max with Xcode from source, but I haven't managed it. I hope to have a solution and/or a successful build for the future. Anyone who can shine a light on this?

**Comment by ediskrad73** [comment] 2019-09-19 14:09
> Ooooh are you serious? Max is one of the most used programs on my Macs. I'm sure I won't upgrade to Catalina if Max won't run.
> I've tried to rebuild Max with Xcode from source, but I haven't managed it. I hope to have a solution and/or a successful build for the future. Anyone who can shine a light on this?

ive switched to XLD in the meantime

**Comment by aprivette** [comment] 2019-10-08 21:07
> ive switched to XLD in the meantime

Thank you for this - I guess I'll use XLD as well and hope someone fixes this.

**Comment by federicochiesa** [comment] 2019-10-09 14:10
I'm not upgrading to Catalina just for this and a few other apps I use... I tried everything to build it from source, I even got it running with dark mode, but as soon as I start a conversion it crashes and I can't fix it.

**Comment by ideoservo** [comment] 2019-11-14 07:11
I've tried building the sources by myself but having too many issues (unicode problem with Norwegian text files, missing 3rd parties libraries such as Flac, wave pack)...

**Comment by ajmas** [comment] 2019-12-09 15:47
Also see issue #17 on 64-bit build, since Max is currently limited to 32-bit macOS.

**Comment by sbooth** [comment] 2020-02-20 13:02
I'm closing this as a duplicate of #17 since the resolution is the same

**Closed by sbooth** 2020-02-20 13:02 UTC
